import { createItem, isEditableItem, type EditableItem, type NbtValue } from '../item/model';
const bare=/^[A-Za-z0-9_.+\-]+$/;
export function stringifySnbt(value:unknown,indent=0):string {
 const pad=' '.repeat(indent), next=indent+2;
 if(value===null)return 'null';
 if(typeof value==='string')return bare.test(value)?value:JSON.stringify(value);
 if(typeof value==='boolean')return value?'1b':'0b';
 if(typeof value==='number')return Number.isInteger(value)?String(value):`${value}d`;
 if(Array.isArray(value))return value.length?`[\n${value.map(v=>`${' '.repeat(next)}${stringifySnbt(v as NbtValue,next)}`).join(',\n')}\n${pad}]`:'[]';
 const entries=Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==undefined);
 return entries.length?`{\n${entries.map(([k,v])=>`${' '.repeat(next)}${bare.test(k)?k:JSON.stringify(k)}: ${stringifySnbt(v as NbtValue,next)}`).join(',\n')}\n${pad}}`:'{}';
}
class Parser{ i=0; constructor(private s:string){} ws(){while(/\s/.test(this.s[this.i]??''))this.i++} value():NbtValue{this.ws();const c=this.s[this.i];if(c==='{')return this.object();if(c==='[')return this.array();if(c==='"'||c==="'")return this.string();const start=this.i;while(this.i<this.s.length&&!/[\s,}\]]/.test(this.s[this.i]))this.i++;const token=this.s.slice(start,this.i);if(/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?[bBsSlLfFdD]?$/.test(token))return Number(token.replace(/[bBsSlLfFdD]$/,''));if(token==='true')return true;if(token==='false')return false;if(!token)throw new Error(`Valor SNBT esperado na posição ${this.i}`);return token} string(){const quote=this.s[this.i++];let out='';while(this.i<this.s.length){const c=this.s[this.i++];if(c===quote)return out;if(c==='\\'){const n=this.s[this.i++];out+=n==='n'?'\n':n==='t'?'\t':n}else out+=c}throw new Error('String SNBT não terminada')} key(){this.ws();return this.s[this.i]==='"'||this.s[this.i]==="'"?this.string():(()=>{const st=this.i;while(this.i<this.s.length&&!/[\s:,{}\[\]]/.test(this.s[this.i]))this.i++;return this.s.slice(st,this.i)})()} object(){const out:Record<string,unknown>={};this.i++;this.ws();while(this.s[this.i]!=='}'){const k=this.key();this.ws();if(this.s[this.i++]!==':')throw new Error(`":" esperado na posição ${this.i-1}`);out[k]=this.value();this.ws();if(this.s[this.i]===','){this.i++;this.ws()}else if(this.s[this.i]!=='}')throw new Error(`"," ou "}" esperado na posição ${this.i}`)}this.i++;return out} array(){const out:NbtValue[]=[];this.i++;this.ws();while(this.s[this.i]!==']'){out.push(this.value());this.ws();if(this.s[this.i]===','){this.i++;this.ws()}else if(this.s[this.i]!==']')throw new Error(`"," ou "]" esperado na posição ${this.i}`)}this.i++;return out}}
export function parseSnbt(text:string):NbtValue{const parser=new Parser(text);const value=parser.value();parser.ws();if(parser.i!==text.length)throw new Error(`Conteúdo inesperado na posição ${parser.i}`);return value}
export function importItemSnbt(text:string):EditableItem{const value=parseSnbt(text);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('O SNBT raiz deve ser um compound');const raw=value as Record<string,NbtValue>;const item={...createItem(String(raw.id??''),Number(raw.count??1)),components:(raw.components??{}) as EditableItem['components']};if(!isEditableItem(item))throw new Error('ItemStack moderno inválido');return item}
